kind: pipeline
type: docker
name: rust-stable

steps:
- name: build
  image: rust
  commands:
  - cargo build --verbose --all

---
kind: pipeline
type: docker
name: rust-beta

steps:
- name: build
  image: rust
  commands:
  - cargo build --verbose --all

---
kind: pipeline
type: docker
name: rust-nightly

steps:
- name: build
  image: rust
  commands:
  - rustup toolchain install nightly
  - rustup default nightly
  - cargo build --verbose --all
